### ISSUE TITLE
Sockets on Linux

### ISSUE THREAD

**Issue by rmcmichael-nist** [usnistgov/optbayesexpt#2]
The demos/instrument_controller.py script runs good under Windows 10 ( 3 out of 3 tested).  But on linux machines, there are error messages, etc.  See below.   Same result for 2 our of 2 tested, both Ubuntu.

--------------------------------------------------------
rdm@Jetson-1:~/Downloads/optbayesexpt/demos/server$ python3 instrument_controller.py 3 runs, each measuring a randomly located peak and specified measurement settings

25 measurement settings between 2 GHz and 3 GHz. Notice the discrete settings
Traceback (most recent call last):
  File "instrument_controller.py", line 261, in <module>
    main()
  File "instrument_controller.py", line 52, in main
    measurement_run(2, 3, 25)
  File "instrument_controller.py", line 92, in measurement_run
    tcpcmd(message)
  File "instrument_controller.py", line 253, in tcpcmd
    connection = connect(default_ip_address, default_port)
  File "instrument_controller.py", line 182, in connect
    connection.connect((ip_address, port))
ConnectionRefusedError: [Errno 111] Connection refused
rdm@Jetson-1:~/Downloads/optbayesexpt/demos/server$
SERVER READY

rdm@Jetson-1:~/Downloads/optbayesexpt/demos/server$ python3 instrument_controller.py
3 runs, each measuring a randomly located peak and specified measurement settings

25 measurement settings between 2 GHz and 3 GHz. Notice the discrete settings
Traceback (most recent call last):
  File "/home/rdm/Downloads/optbayesexpt/demos/server/server_script.py", line 91, in <module>
    nanny = CustomServer(initial_args=args)
  File "/home/rdm/Downloads/optbayesexpt/demos/server/server_script.py", line 65, in __init__
    ip_address=ip_address, port=port)
  File "/usr/local/lib/python3.6/dist-packages/optbayesexpt-1.0.0-py3.6.egg/optbayesexpt/obe_server.py", line 47, in __init__
  File "/usr/local/lib/python3.6/dist-packages/optbayesexpt-1.0.0-py3.6.egg/optbayesexpt/obe_socket.py", line 57, in __init__
OSError: [Errno 98] Address already in use
    "X" out to proceed.

Higher resolution now. 200 measurement settings between 2 GHz and 3 GHz.
    "X" out to proceed.

A tricky one.  200 Measurement settings from 1 GHz to 4 GHz.
The measurements probably won't extend all the way from 1 to 4, though.
This is because the prior (see server script) only expects center values from 1.5 to 3.5
    "X" out to proceed.
rdm@Jetson-1:~/Downloads/optbayesexpt/demos/server$

**Comment by SMB784** [comment]
Behavior on Ubuntu 18.04 LTS (first run with python which fails. running with python3 works but throws error, screenshots attached)

----------------------------------------------------------------------------------------------------------------------------

**(base) sean@kerberos:~/workspace/NIST/optbayesexpt/demos/server$ python instrument_controller.py** 
3 runs, each measuring a randomly located peak and specified measurement settings

25 measurement settings between 2 GHz and 3 GHz. Notice the discrete settings
Traceback (most recent call last):
  File "instrument_controller.py", line 258, in <module>
    main()
  File "instrument_controller.py", line 49, in main
    measurement_run(2, 3, 25)
  File "instrument_controller.py", line 89, in measurement_run
    tcpcmd(message)
  File "instrument_controller.py", line 250, in tcpcmd
    connection = connect(default_ip_address, default_port)
  File "instrument_controller.py", line 179, in connect
    connection.connect((ip_address, port))
ConnectionRefusedError: [Errno 111] Connection refused

-----------------------------------------------------------------------------------------------------------------------

**(base) sean@kerberos:~/workspace/NIST/optbayesexpt/demos/server$ python3 instrument_controller.py** 
3 runs, each measuring a randomly located peak and specified measurement settings

25 measurement settings between 2 GHz and 3 GHz. Notice the discrete settings
Traceback (most recent call last):
  File "/home/sean/workspace/NIST/optbayesexpt/demos/server/server_script.py", line 91, in <module>
    nanny = CustomServer(initial_args=args)
  File "/home/sean/workspace/NIST/optbayesexpt/demos/server/server_script.py", line 65, in __init__
    ip_address=ip_address, port=port)
  File "/home/sean/miniconda3/lib/python3.7/site-packages/optbayesexpt-1.0.0-py3.7.egg/optbayesexpt/obe_server.py", line 47, in __init__
  File "/home/sean/miniconda3/lib/python3.7/site-packages/optbayesexpt-1.0.0-py3.7.egg/optbayesexpt/obe_socket.py", line 57, in __init__
OSError: [Errno 98] Address already in use
QApplication: invalid style override passed, ignoring it.
    "X" out to proceed.

Higher resolution now. 200 measurement settings between 2 GHz and 3 GHz.  
    "X" out to proceed.

A tricky one.  200 Measurement settings from 1 GHz to 4 GHz.
The measurements probably won't extend all the way from 1 to 4, though.
This is because the prior (see server script) only expects center values from 1.5 to 3.5
    "X" out to proceed.

![OBED_SocketError_Python3_LowRes2-3GHz](https://user-images.githubusercontent.com/14501817/83654939-c9a08980-a58b-11ea-926b-10ea718ba9d0.png)

![OBED_SocketError_Python3_HiRes2-3GHz](https://user-images.githubusercontent.com/14501817/83654963-cf966a80-a58b-11ea-8776-15a74cb5b807.png)

![OBED_SocketError_Python3_HiRes1-4GHz](https://user-images.githubusercontent.com/14501817/83654989-d7560f00-a58b-11ea-8e35-a997ef5e9fd4.png)

**Comment by rmcmichael-nist** [comment]
Adding a sleep(3) to the demos/instrument_controller.py script after it launches the server script yields clean operation.  I think the problem is that instrument_controller tries to communicate with the server before the server is finished setting up.

**Comment by rmcmichael-nist** [comment]
Resolved:  added a try-except to handle ConnectionRefusedError using a new 'ready' command in OBE_Server.run()
